version: "3.8"
services:
  view:
    image: message-app-view-dev
    container_name: message-app-view-dev
    build:
      context: .
      dockerfile: ./services/view/Dockerfile.dev
    volumes:
      - ./services/view:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - grpc-gateway

  streaming:
    image: message-app-streaming-dev
    container_name: message-app-streaming-dev
    build:
      context: ./services/streaming
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/streaming:/app
      - /app/node_modules
    env_file:
      - ./services/streaming/.env.dev
    depends_on:
      - messagech

  auth:
    image: message-app-auth-dev
    container_name: message-app-auth-dev
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/auth:/app
    env_file:
      - ./services/auth/.env.dev

  chat:
    image: message-app-chat-dev
    container_name: message-app-chat-dev
    user: ${MY_UID}:${MY_GID} # to make the host be able to modify or delete files created in the container
    build:
      context: ./services/chat
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/chat:/app
    env_file:
      - ./services/chat/.env.dev
    depends_on:
      - chatdb

  chatdb:
    image: postgres:16-alpine
    container_name: message-app-chatdb-dev
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ./services/chatdb/data/dev:/var/lib/postgresql/data
    ports:
      - 5432:5432

  messagech:
    image: ghcr.io/microsoft/garnet-alpine
    container_name: message-app-messagech-dev

  reverse-proxy:
    image: nginx:stable-alpine
    container_name: message-app-reverse-proxy-dev
    volumes:
      - ./services/reverse-proxy/nginx.conf.dev:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:80
    depends_on:
      - auth
      - view

  grpc-gateway:
    image: envoyproxy/envoy:distroless-v1.30-latest
    container_name: message-app-grpc-gateway-dev
    volumes:
      - ./services/grpc-gateway/envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - auth

  pgadmin:
    image: dpage/pgadmin4
    container_name: message-app-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.com
      PGADMIN_DEFAULT_PASSWORD: dev
    logging:
      driver: none
    ports:
      - 5050:80
