version: "3.8"
services:
  view:
    image: message-app-view-dev
    container_name: message-app-view-dev
    build:
      context: .
      dockerfile: ./services/view/Dockerfile.dev
    volumes:
      - ./services/view:/app
      - /app/protos
      - /app/node_modules
      - /app/.next
    depends_on:
      - grpc-proxy

  auth:
    image: message-app-auth-dev
    container_name: message-app-auth-dev
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/auth:/app
    env_file:
      - ./services/auth/.env.dev

  chat:
    image: message-app-chat-dev
    container_name: message-app-chat-dev
    build:
      context: ./services/chat
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/chat:/app
    env_file:
      - ./services/chat/.env.dev
    depends_on:
      - chatdb

  chatdb:
    container_name: message-app-chatdb-dev
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ./services/chatdb/data/dev:/var/lib/postgresql/data
    ports:
      - 5432:5432

  reverse-proxy:
    image: nginx:stable-alpine
    container_name: message-app-reverse-proxy-dev
    volumes:
      - ./services/reverse-proxy/nginx.conf.dev:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:80
    depends_on:
      - auth
      - view

  grpc-proxy:
    image: envoyproxy/envoy:distroless-v1.30-latest
    volumes:
      - ./services/grpc-proxy/envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - auth

  pgadmin:
    container_name: message-app-pgadmin-dev
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.com
      PGADMIN_DEFAULT_PASSWORD: dev
    logging:
      driver: none
    ports:
      - 5050:80
