services:
  view:
    container_name: message-app-view-prod
    build:
      context: ./services/view
      dockerfile: Dockerfile.prod
    env_file:
      - ./services/view/.env.prod
    depends_on:
      - grpc-gateway

  streaming:
    container_name: message-app-streaming-prod
    build:
      context: ./services/streaming
      dockerfile: Dockerfile.prod
    env_file:
      - ./services/streaming/.env.prod
    depends_on:
      - messagech

  auth:
    # image: message-app-auth-dev
    container_name: message-app-auth-prod
    build:
      context: ./services/auth
      dockerfile: Dockerfile.prod
    env_file:
      - ./services/auth/.env.prod

  chat:
    # image: message-app-chat-dev
    container_name: message-app-chat-prod
    build:
      context: ./services/chat
      dockerfile: Dockerfile.prod
    env_file:
      - ./services/chat/.env.prod

  messagech:
    image: ghcr.io/microsoft/garnet-alpine
    container_name: message-app-messagech-prod

  reverse-proxy:
    image: nginx:stable-alpine
    container_name: message-app-reverse-proxy-prod
    volumes:
      - ./services/reverse-proxy/nginx.conf.prod:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - auth
      - view

  grpc-gateway:
    image: envoyproxy/envoy:distroless-v1.30-latest
    container_name: message-app-grpc-gateway-prod
    volumes:
      - ./services/grpc-gateway/envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - auth

  pgadmin:
    image: dpage/pgadmin4
    container_name: message-app-pgadmin-prod
    environment:
      PGADMIN_DEFAULT_EMAIL: prod@prod.com
      PGADMIN_DEFAULT_PASSWORD: prod
    logging:
      driver: none
    ports:
      - 5050:80
